### ISSUE TITLE
Host x.x.x.x doesn't support protocol version 

### ISSUE THREAD

**Issue by christopher-t-mooney** [avalanche123/cassandra-web#5]
Hi!

I'm trying to use cassandra-web with the servers in my cassandra cluster.  But when I try to start it I get the following output (I removed the actual ip addresses):

cassandra-web --hosts 'x.x.x.x,y.y.y.y,z.z.z.z'

INFO -- : Establishing control connection
INFO -- : Host x.x.x.x doesn't support protocol version 2, downgrading
WARN -- : Host x.x.x.x refused all connections
Cassandra::Errors::ProtocolError: Invalid or unsupported protocol version (1); the lowest supported version is 3 and the greatest is 4

If I run cqlsh, here is the information it gives:
[cqlsh 5.0.1 | Cassandra 3.9 | CQL spec 3.4.2 | Native protocol v4]

**Comment by avalanche123** [comment]
what version of the cassandra-driver are you using?

**Comment by christopher-t-mooney** [comment]
How would i find that out?

**Comment by avalanche123** [comment]
```ruby
require 'cassandra/version'

p Cassandra::VERSION
```

how are you installing this project? what is the contents of your gemfile.lock

**Comment by christopher-t-mooney** [comment]
Ah, well, I am creating a docker container for it, so essentially, I use the official ruby image for docker and use the following command in the dockerfile to install it:

RUN gem install cassandra-web

Which builds the whole thing for me (looks like the cassandra driver might be 1.2.0?):

fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/26) Installing binutils-libs (2.26-r0)
(2/26) Installing binutils (2.26-r0)
(3/26) Installing gmp (6.1.0-r0)
(4/26) Installing isl (0.14.1-r0)
(5/26) Installing libgomp (5.3.0-r0)
(6/26) Installing libatomic (5.3.0-r0)
(7/26) Installing libgcc (5.3.0-r0)
(8/26) Installing mpfr3 (3.1.2-r0)
(9/26) Installing mpc1 (1.0.3-r0)
(10/26) Installing libstdc++ (5.3.0-r0)
(11/26) Installing gcc (5.3.0-r0)
(12/26) Installing make (4.1-r1)
(13/26) Installing musl-dev (1.1.14-r14)
(14/26) Installing libc-dev (0.7-r0)
(15/26) Installing fortify-headers (0.8-r0)
(16/26) Installing g++ (5.3.0-r0)
(17/26) Installing build-base (0.4-r1)
(18/26) Installing libedit (20150325.3.1-r3)
(19/26) Installing ruby-libs (2.3.1-r0)
(20/26) Installing ruby (2.3.1-r0)
(21/26) Installing ruby-bigdecimal (2.3.1-r0)
(22/26) Installing libgmpxx (6.1.0-r0)
(23/26) Installing gmp-dev (6.1.0-r0)
(24/26) Installing ruby-dev (2.3.1-r0)
(25/26) Installing ruby-io-console (2.3.1-r0)
(26/26) Installing sudo (1.8.16-r0)
Executing busybox-1.24.2-r12.trigger
OK: 194 MiB in 55 packages
Successfully installed ione-1.2.4
Building native extensions.  This could take a while...
Successfully installed cassandra-driver-1.2.0
Successfully installed rack-1.6.5
Building native extensions.  This could take a while...
Successfully installed eventmachine-1.2.1
Successfully installed daemons-1.2.4
Building native extensions.  This could take a while...
Successfully installed thin-1.7.0
Successfully installed rack-cors-0.4.0
Successfully installed rack-parser-0.7.0
Successfully installed tilt-2.0.5
Successfully installed rack-protection-1.5.3
Successfully installed sinatra-1.4.7
Building native extensions.  This could take a while...
Successfully installed lz4-ruby-0.3.3
Successfully installed cassandra-web-0.3.0
13 gems installed

**Comment by avalanche123** [comment]
ok I've just pushed a bumped version of this gem that uses a newer driver

**Comment by christopher-t-mooney** [comment]
Dude! you rock!  It works perfectly now!

Thank you!  Especially for being so quick to respond.

**Comment by avalanche123** [comment]
no problem, enjoy!
