### ISSUE TITLE
Open Source License?

### ISSUE THREAD

**Issue by bskarda** [avalanche123/cassandra-web#9]
It would be great if this project was formally open sourced by adding a license to the repository. That would open up use of the project to a lot of organizations and end users. Without a license it's unclear how users are allowed to consume the source of this project.

Here's some more information from Github on choosing a license https://help.github.com/articles/licensing-a-repository/

**Comment by bmrobin** [comment]
seconded, really love the tool and would love to have the ability to officially/legally integrate this into an existing webapp of mine

**Comment by avikivity** [comment]
I'm also interested in integrating this into https://guthub.com/scylladb/scylla.

**Comment by avalanche123** [comment]
If someone can send MIT license PR, I’ll take it

**Comment by bmrobin** [comment]
https://github.com/avalanche123/cassandra-web/pull/28

**Comment by avalanche123** [comment]
Thanks!

**Comment by ned-kelly** [comment]
@avikivity - I tried getting it going with `scylladb` but I kept seeing: `

```Cassandra::Cluster::Schema::CQLTypeParser::IncompleteTypeError: unable to lookup type "duration"```

I'd be keen to use this with it, if you want me to raise this in the scylladb git repo?

**Comment by avikivity** [comment]
This is probably a driver error. What driver are you using? Maybe you're using an outdated version?

**Comment by bmrobin** [comment]
@avikivity @ned-kelly can you move this to a separate issue for discussion?
